export const GET_TICKERS_REQUESTED = 'GET_TICKERS_REQUESTED';
export const GET_TICKERS_CURRENT = 'GET_TICKERS_CURRENT';
export const GET_TICKERS_PREVIOUS = 'GET_TICKERS_PREVIOUS';
export const GET_TICKERS_ERROR = 'GET_TICKERS_ERROR';